# Generated by Django 2.1.2 on 2018-10-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triumph_app', '0004_auto_20171115_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='sequence',
            field=models.CharField(max_length=999, verbose_name='Выражение'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='coefficient',
            field=models.PositiveIntegerField(default=1, verbose_name='Множитель'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_title',
            field=models.CharField(max_length=255, verbose_name='Название темы'),
        ),
    ]
